[project]
name = "midi-event-handler"
version = "0.1.0"
description = ""
authors = [
    {name = "Julien LANCELOT",email = "julien.lancelot@enovasense.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4"
dependencies = [
    "mido (>=1.3.3,<2.0.0)",
    "fastapi[standard] (>=0.116.0,<0.117.0)",
    "pyyaml (>=6.0.2,<7.0.0)",
]

[tool.poetry]
packages = [{include = "midi_event_handler", from = "src"}]

[tool.poetry.scripts]
start = "midi_event_handler.entrypoint:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
